# Alpine pyhon image with uv installed
FROM ghcr.io/astral-sh/uv:0.8-python3.13-alpine

# Install psycopg2-binary
RUN apk add build-base libpq libpq-dev && apk add libffi-dev

# Install the project into `/app`
WORKDIR /app

COPY . /app
RUN uv sync --locked --no-dev --group production

# Inform Docker that the application will listen on port 8000
EXPOSE 8000

ENTRYPOINT ["sh", "/app/docker/entrypoint.sh"]
