from api.game_registery import GameServiceRegistry
from api.services.game_modes.game_guess_capital_from_country_base import GameServiceGuessCapitalFromCountryBase
from core.models.user_country_score import GameModes


@GameServiceRegistry.register(GameModes.GUESS_CAPITAL_FROM_COUNTRY_TRAINING_INFINITE)
class GameServiceGuessCapitalFromCountryTrainingInfinite(GameServiceGuessCapitalFromCountryBase):
    GAME_MODE = GameModes.GUESS_CAPITAL_FROM_COUNTRY_TRAINING_INFINITE
