# Generated by Django 5.2 on 2025-04-28 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_fr", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_correct", models.BooleanField()),
            ],
            options={
                "verbose_name_plural": "guesses",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_fr", models.CharField(max_length=100)),
                ("name_native", models.CharField(max_length=100)),
                ("iso2_code", models.CharField(max_length=2, unique=True)),
                ("iso3_code", models.CharField(max_length=3, unique=True)),
                ("continent", models.CharField(max_length=100)),
                (
                    "capital_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="country_capital_city",
                        to="core.city",
                    ),
                ),
                ("cities", models.ManyToManyField(to="core.city")),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ("name_en",),
            },
        ),
        migrations.CreateModel(
            name="UserCountryScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_mode",
                    models.CharField(
                        choices=[
                            ("GUESS_COUNTRY_FROM_FLAG", "Guess Country From Flag"),
                            (
                                "GUESS_CAPITAL_FROM_COUNTRY",
                                "Guess Capital From Country",
                            ),
                        ]
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.country"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_guesses",
                    models.ManyToManyField(
                        blank=True, related_name="user_guesses", to="core.guess"
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "unique_together": {("country", "game_mode", "user")},
            },
        ),
    ]
