# Generated by Django 5.2 on 2025-05-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ("name_en",), "verbose_name_plural": "cities"},
        ),
        migrations.RemoveField(
            model_name="country",
            name="capital_city",
        ),
        migrations.AddField(
            model_name="city",
            name="capital_of_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capital_cities",
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="name_native",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="guess",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
