# Generated by Django 5.2 on 2025-05-08 15:34

from core.models.Country import flag_upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_city_options_remove_country_capital_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="flag",
            field=models.ImageField(
                null=True, upload_to=flag_upload_path
            ),
        ),
    ]
