# Generated by Django 5.2 on 2025-05-16 14:40

import core.models.country
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from core.models.country import flag_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_email_verified_user_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name_en',), 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name_en',), 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='guess',
            options={'ordering': ('created_at',), 'verbose_name': 'guess', 'verbose_name_plural': 'guesses'},
        ),
        migrations.AlterModelOptions(
            name='usercountryscore',
            options={'ordering': ('created_at',), 'verbose_name': 'user country score', 'verbose_name_plural': 'user country scores'},
        ),
        migrations.AlterField(
            model_name='city',
            name='is_capital',
            field=models.BooleanField(default=False, help_text='Several cities can be capital cities of a country (e.g, South Africa).', verbose_name='Is capital city'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_fr',
            field=models.CharField(max_length=100, verbose_name='French name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cities',
            field=models.ManyToManyField(related_name='countries', to='core.city', verbose_name='Cities'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('AN', 'Antarctica')], max_length=100, verbose_name='Continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=flag_upload_path, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2_code',
            field=models.CharField(max_length=2, unique=True, verbose_name='iso2 code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='iso3 code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='English name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_fr',
            field=models.CharField(max_length=100, verbose_name='French name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_native',
            field=models.CharField(max_length=100, verbose_name='Native name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='wikidata_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Wikidata ID'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='guess',
            name='is_correct',
            field=models.BooleanField(verbose_name='is correct'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='is email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='usercountryscore',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_scores', to='core.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='usercountryscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='usercountryscore',
            name='game_mode',
            field=models.CharField(choices=[('GUESS_COUNTRY_FROM_FLAG', 'Guess Country From Flag'), ('GUESS_CAPITAL_FROM_COUNTRY', 'Guess Capital From Country')], verbose_name='game mode'),
        ),
        migrations.AlterField(
            model_name='usercountryscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='usercountryscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='usercountryscore',
            name='user_guesses',
            field=models.ManyToManyField(blank=True, related_name='user_guesses', to='core.guess', verbose_name='user guesses'),
        ),
    ]
