# Generated by Django 5.2 on 2025-05-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_country_flag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="name_native",
        ),
    ]
