# Generated by Django 5.2 on 2025-05-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_city_name_native"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="capital_of_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capital_cities",
                to="core.country",
            ),
        ),
    ]
