# Generated by Django 5.2 on 2025-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercountryscore',
            name='user_guesses',
            field=models.ManyToManyField(blank=True, related_name='user_scores', to='core.guess', verbose_name='user guesses'),
        ),
    ]
