# Generated by Django 5.2 on 2025-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usercountryscore_user_guesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercountryscore',
            name='game_mode',
            field=models.CharField(choices=[('GCFF_TRAINING_INFINITE', 'Guess Country From Flag - Training Infinite'), ('GCFF_CHALLENGE_COMBO', 'Guess Country From Flag - Challenge Combo'), ('GCFC_TRAINING_INFINITE', 'Guess Capital From Country - Training Infinite'), ('GCFC_CHALLENGE_COMBO', 'Guess Capital From Country - Challenge Combo')], verbose_name='game mode'),
        ),
    ]
