# Generated by Django 5.2 on 2025-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_city_capital_of_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="wikidata_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
