# Generated by Django 5.2 on 2025-05-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_country_wikidata_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="capital_of_country",
        ),
        migrations.AddField(
            model_name="city",
            name="is_capital",
            field=models.BooleanField(
                default=False,
                help_text="Several cities can be capital cities of a country (e.g, South Africa).",
            ),
        ),
    ]
