# Generated by Django 5.2 on 2025-08-23 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usercountryscore_game_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('game_mode', models.CharField(choices=[('GCFF_TRAINING_INFINITE', 'Guess Country From Flag - Training Infinite'), ('GCFF_CHALLENGE_COMBO', 'Guess Country From Flag - Challenge Combo'), ('GCFC_TRAINING_INFINITE', 'Guess Capital From Country - Training Infinite'), ('GCFC_CHALLENGE_COMBO', 'Guess Capital From Country - Challenge Combo')], verbose_name='game mode')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Best streak')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user stat',
                'verbose_name_plural': 'user stats',
                'ordering': ('created_at',),
                'unique_together': {('user', 'game_mode')},
            },
        ),
    ]
