# Generated by Django 5.2 on 2025-08-26 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferenceGameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('GCFF_TRAINING_INFINITE', 'Guess Country From Flag - Training Infinite'), ('GCFF_CHALLENGE_COMBO', 'Guess Country From Flag - Challenge Combo'), ('GCFC_TRAINING_INFINITE', 'Guess Capital From Country - Training Infinite'), ('GCFC_CHALLENGE_COMBO', 'Guess Capital From Country - Challenge Combo')], max_length=255)),
                ('show_tips', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference_game_modes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User preference by game mode',
                'verbose_name_plural': 'User preference by game modes',
                'unique_together': {('user', 'game_mode')},
            },
        ),
    ]
