# Generated by Django 5.2.5 on 2025-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userpreferencegamemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='wikipedia_link_en',
            field=models.URLField(default='https://fr.wikipedia.org/wiki/', verbose_name='English Wikipedia Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='wikipedia_link_fr',
            field=models.URLField(default='https://fr.wikipedia.org/wiki/', verbose_name='French Wikipedia Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='wikipedia_link_en',
            field=models.URLField(default='https://fr.wikipedia.org/wiki/', verbose_name='English Wikipedia Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='wikipedia_link_fr',
            field=models.URLField(default='https://fr.wikipedia.org/wiki/', verbose_name='French Wikipedia Link'),
            preserve_default=False,
        ),
    ]
