# Generated by Django 5.2.5 on 2025-09-09 13:41

from django.db import migrations

from core.models.wikipedia_link import WikipediaLink


def add_default_wikipedia_links(apps, schema_editor):
    Country = apps.get_model("core", "Country")
    City = apps.get_model("core", "City")

    countries = Country.objects.all()
    cities = City.objects.all()

    for country in countries:
        country.wikipedia_link_fr = WikipediaLink.build_wikipedia_link(country.name_fr, "fr")
        country.wikipedia_link_en = WikipediaLink.build_wikipedia_link(country.name_en, "en")

    for city in cities:
        city.wikipedia_link_fr = WikipediaLink.build_wikipedia_link(city.name_fr, "fr")
        city.wikipedia_link_en = WikipediaLink.build_wikipedia_link(city.name_en, "en")

    Country.objects.bulk_update(countries, ["wikipedia_link_fr", "wikipedia_link_en"])
    City.objects.bulk_update(cities, ["wikipedia_link_fr", "wikipedia_link_en"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_city_wikipedia_link_en_city_wikipedia_link_fr_and_more"),
    ]

    operations = [migrations.RunPython(add_default_wikipedia_links, reverse_code=migrations.RunPython.noop)]
